numero = 5
if numero == 10:
    raise Exception
print('fim')